In [1]:
import math as mth
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from scipy.sparse import csr_matrix
import os
import random   
from scipy.sparse import csr_matrix
import networkx as nx

In [2]:
#Generiamo una matrice sparsa, con m entrate non nulle e uguali a 1 per riga
def generate_sparse_matrix(n_righe, n_colonne, m=5):

    # Genero gli indici di riga per inserire i k valori non nulli
    righe = np.repeat(np.arange(n_righe), m)        #Generiamo righe lunghe n_righe*m di elemnti da 0 a n_rows-1 ripetuto m volte

    colonne = np.empty(n_righe * m, dtype=np.int32) #Generiamo colonne lunghe n_righe*m di numeri casuali interi a 32 bit (per conservare memoria)                      

    for i in range(n_righe):
        n_colonne_corrette = np.delete(np.arange(n_colonne), i)
        #Generiamo un array di numeri casuali di lunghezza n_colonne in cui eliminiamo l'elemento dellìindice del ciclo
        colonne[i*m:(i+1)*m] = np.random.choice(n_colonne_corrette, size=m, replace=False)         
        #Selezioniamo m diversi elemnti delle colonne corrette senza ripetizioni e le salvo al posto delle colonne di indice [i*m:(i+1)*m]
                                                                                 
        #Creo quindi indici di riga e colonna a cui successivamente attribuisco valore 1 
   
    valori= np.ones(n_righe * m)

    return csr_matrix((valori, (righe, colonne)), shape=(n_righe, n_colonne))

In [3]:
# Parametri per la matrice sparsa
N,m=20,5                  
n_righe = N
n_colonne = N

In [4]:
A = generate_sparse_matrix(n_righe, n_colonne, m)
print(A)
print(A.toarray())

  (0, 1)	1.0
  (0, 6)	1.0
  (0, 7)	1.0
  (0, 9)	1.0
  (0, 11)	1.0
  (1, 0)	1.0
  (1, 5)	1.0
  (1, 10)	1.0
  (1, 12)	1.0
  (1, 14)	1.0
  (2, 1)	1.0
  (2, 6)	1.0
  (2, 10)	1.0
  (2, 12)	1.0
  (2, 18)	1.0
  (3, 8)	1.0
  (3, 10)	1.0
  (3, 15)	1.0
  (3, 16)	1.0
  (3, 17)	1.0
  (4, 0)	1.0
  (4, 9)	1.0
  (4, 14)	1.0
  (4, 15)	1.0
  (4, 17)	1.0
  :	:
  (15, 0)	1.0
  (15, 9)	1.0
  (15, 10)	1.0
  (15, 14)	1.0
  (15, 18)	1.0
  (16, 1)	1.0
  (16, 4)	1.0
  (16, 8)	1.0
  (16, 11)	1.0
  (16, 12)	1.0
  (17, 0)	1.0
  (17, 7)	1.0
  (17, 10)	1.0
  (17, 13)	1.0
  (17, 16)	1.0
  (18, 8)	1.0
  (18, 12)	1.0
  (18, 14)	1.0
  (18, 15)	1.0
  (18, 16)	1.0
  (19, 1)	1.0
  (19, 3)	1.0
  (19, 8)	1.0
  (19, 12)	1.0
  (19, 14)	1.0
[[0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0

In [16]:
out_dir="figures_networks_directed" #Sto creando una cartella (a me la crea in download) dove verranno salvati queste immagini 
os.makedirs(out_dir,exist_ok=True)  #Sto dicendo che se esiste già la cartella non crearne una nuova (una sorta di check)

n=15  # numero nodi (penso scelti arbitrariamente) il grafo avrà 15 nodi numerati da 0 a 14

#Sto generando grafo diretto Erdős–Rényi per poi calcolarne la matrice di adiacenza, lo sto facendo perché nel problema 4 diceva di provare poi ad usare diverse matrici di adiacenza
p=0.2
G_er=nx.gnp_random_graph(n,p,seed=1,directed=True) #è una funzione della libreria Networks che crea un grafo casuale secondo il modello di Erdős–Rényi, i parametri sono n = numedo di nodi, p = probabilità di creare un arco diretto tra ogni coppia di nodi, directed = true Crea archi diretti, cioè orientati da un nodo all’altro
A_er=nx.to_numpy_array(G_er,dtype=int) #Converto il grafo G_er in una matrice di adiacenza rappresentata come un array

#costruisco un grafo diretto basato sul modello di Watts–Strogatz (detto anche piccolo mondo)
k=3;                                                 #ogni nodo sarà inizialmente connesso ai 3 vicini più prossimi su ciascun lato
beta=0.2                                             #probabilità di ricollegare ogni arco a un nodo casuale (introduce casualità)
G_ws=nx.watts_strogatz_graph(n,k,beta,seed=2)        #Creo un grafo non diretto
G_ws_dir=nx.DiGraph()                                #Creo un nuovo grafo diretto vuoto
G_ws_dir.add_nodes_from(G_ws.nodes())                #Aggiungo nel grafo diretto vuoto tutti i nodi
for u,v in G_ws.edges():                             #per ogni arco non diretto (u,v) in G_ws si genera un numero casuale
    if np.random.rand()<0.5:                         #se il numero generato è minore di 0.5 
        G_ws_dir.add_edge(u,v)                       #aggiungo un arco u -> v
    else:
        G_ws_dir.add_edge(v,u)                       #altrimenti aggiungo un arco v -> u
A_ws=nx.to_numpy_array(G_ws_dir,dtype=int)           #converte il grafo in una martice di adiacenza

#Costruisco un grafo Barabási–Albert diretto
m=3                                                  #ogni nodo si connette ad m nodi già esistenti 
G_ba=nx.barabasi_albert_graph(n,m,seed=3)            #parto da un grafo iniziale ad ogni passo aggiunge un nuovo nodo che si collega a m nodi già esistenti, i nodi più collegati hanno più probabilità di essere scelti
G_ba_dir=nx.DiGraph()                                #creo un grafo vuoto
G_ba_dir.add_nodes_from(G_ba.nodes())                #aggiungo tutti i nodi all'interno del grafo       
for u,v in G_ba.edges():                             #per ogni arco (u,v) non diretto        
    if u>v:                                          #se u>v crea un arco da u -> v altrimenti il viceversa
        G_ba_dir.add_edge(u,v)
    else:
        G_ba_dir.add_edge(v,u)
A_ba=nx.to_numpy_array(G_ba_dir,dtype=int)           #converte il grafo in una matrice di adiacenza

#Creo una unzione per salvare PNG le mie mappe
def save_matrix_png(A,name):
    plt.figure(figsize=(5,5))
    plt.imshow(A,cmap="Greys",interpolation="nearest")
    plt.title(name)
    plt.colorbar()
    path=os.path.join(out_dir,f"{name}.png")
    plt.savefig(path,bbox_inches="tight")
    plt.close()
    return path
p1=save_matrix_png(A_er,"ER_directed_10x10_p04")
p2=save_matrix_png(A_ws,"WS_directed_10x10_k2_b05")
p3=save_matrix_png(A_ba,"BA_directed_10x10_m2")